### ISSUE TITLE
Deploy SQL Server Reporting files task failed.

### ISSUE THREAD

**Issue by dvaibhav181** [tobania/VSTS.Extension.SqlReportingServices#24]
While running the release definition for deploying .rdl files on SQL server reporting services, the release is failing with below error.

2017-09-14T20:00:33.1011703Z ##[error]System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The remote name could not be resolved: 'azfbissp01'
2017-09-14T20:00:33.1011703Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2017-09-14T20:00:33.1031742Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2017-09-14T20:00:33.1031742Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2017-09-14T20:00:33.1031742Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2017-09-14T20:00:33.1031742Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2017-09-14T20:00:33.1031742Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
2017-09-14T20:00:33.1171918Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.

![image](https://user-images.githubusercontent.com/18335623/30456018-d2cb5664-9956-11e7-9d6b-3617e09ee234.png)

![image](https://user-images.githubusercontent.com/18335623/30456093-2048e8f2-9957-11e7-862a-7b96be872dbc.png)

Could you please let me know how to resolve this issue?

**Comment by muziekklas** [comment]
Looks to me that you are using the hosted Build servers of VSTS, which cannot find your reporting service.
Can you make a new PS Task and try pinging it? (ping MyReportingService)

Also take a look at the complete URL you are required to use: http(s)://[ServernameFQDN]/ReportServer/ReportService2010.asmx?wsdl
without this, the script cannot access the soap service.

**Comment by muziekklas** [comment]
@dvaibhav181 Any update or can we close this?

**Comment by dvaibhav181** [comment]
You can close it.

Thanks,
Vaibhav
