### ISSUE TITLE
The underlying connection was closed: An unexpected error occurred on a receive.

### ISSUE THREAD

**Issue by ndham** [tobania/VSTS.Extension.SqlReportingServices#64]
Using this for my different environment. Not putting my production deployment and it starts the process and then stops in the middle giving this error "The underlying connection was closed: An unexpected error occurred on a receive. 2022-05-01T12:00:59.6093931Z ##[error]PowerShell script completed with 1 errors." did anybody received that issue?

The timeout is set to 0

**Comment by HannahVernon** [comment]
we're seeing a similar issue:

```
2024-01-24T23:00:53.2986430Z [VERBOSE] >> WsPassword: ******** -
2024-01-24T23:00:53.2986823Z 
2024-01-24T23:00:53.2986975Z 
2024-01-24T23:00:53.3059546Z Uploading files
2024-01-24T23:00:53.3145987Z Creating WebService proxy using credentials
2024-01-24T23:00:53.3146531Z 
2024-01-24T23:00:53.3146719Z 
2024-01-24T23:00:53.4130599Z ##[error]System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The underlying connection was closed: An unexpected error occurred on a send.
2024-01-24T23:00:53.4137900Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2024-01-24T23:00:53.4138712Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2024-01-24T23:00:53.4139480Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2024-01-24T23:00:53.4140462Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2024-01-24T23:00:53.4141336Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2024-01-24T23:00:53.4142131Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
2024-01-24T23:00:53.4494866Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.
2024-01-24T23:00:53.4504929Z ##[section]Finishing: Deploy SQL Server reporting files
```
